### PR TITLE
GitHub Actions: Test on current versions of Node.js

### PR DESCRIPTION
**Pull request by cclauss**
Do we really need `npm install -g node-gyp`?

### CODE REVIEW

**Comment by lwahonen** [comment]
I merged these but the tests still look broken

**Comment by cclauss** [comment]
The tests are broken on modern versions of Node.js. because this code needs real maintenance...
* https://github.com/nodejs/node-gyp/issues?q=ffi-napi
* https://github.com/node-ffi-napi/node-ffi-napi/issues
* https://github.com/node-ffi-napi/node-ffi-napi/issues/247
* node-ffi-napi/node-ffi-napi#255
* node-ffi-napi/node-ffi-napi#253
* https://github.com/node-ffi-napi/node-ffi-napi/issues/257

**Comment by Kreijstal** [comment]
also dependencies are ancient. Someone has to fork node-gyp as well, it is not mantained as far as I can see

**Comment by cclauss** [comment]
@Kreijstal Please look at node-ffi-napi/node-ffi-napi#269 as mentioned above for workarounds.

**Pull request merged**
